### ISSUE TITLE
Homepage content is not visible

### ISSUE THREAD

**Issue by nasirkhan** [creativecommons/wp-theme-cc-chapter#31]
## Describe the bug
Hi, i think the our chapter website have some issue, the home page is not showing any content. I tried to change the page from the admin panel also and it did not solve the issue. When a page is not set as home, contents displayed properly. 

Chapter website: https://bd.creativecommons.net/
 
## To Reproduce

1. Go to https://bd.creativecommons.net/

Only the header and footer is visible, page content is not showing here. 

## Expected behavior
There are contents on the page. Which should be visible between header and footer area.

## Screenshots
![Screenshot_2020-03-17 Share, Collaborate, Remix, Reuse - CC Bangladesh](https://user-images.githubusercontent.com/396987/76881504-70399000-68a3-11ea-9a17-d58dda12f90a.png)

## Desktop (please complete the following information)
 - OS: (ex. iOS) Ubuntu 18.04
 - Browser (ex. chrome, safari) Firefox
 - Version (ex. 22) 74 (64bit)

**Comment by hugosolar** [comment]
Hello @nasirkhan 
Sorry for my late reply but you need to set some widgets along the homepage in order to show the content in the way you want.
There's a [backend guide](https://drive.google.com/open?id=11PEKaaO_zbE6Avdc2u4lP05pe7fcUZl22BPAcRlaoQ8) you can follow and please don't hesitate to reach me if you need any help or further questions.
